### ISSUE TITLE
Dynamically get dimension of monitor

### ISSUE THREAD

**Issue by adzo261** [adzo261/todo-wallpaper-cli#1]
Currently, we are using default dimensions assumed for a laptop/desktop.
Add support for dynamically fetching monitor dimension required for setting the wallpaper.

https://github.com/adzo261/todo-wallpaper-cli/blob/947722e29bbe05f9d64df65148e13b751010cf00/wallpaper.py#L14

**Comment by yashBhosale** [comment]
Hi, I'm a beginner and I'd like to take this on. It seems that the 2 main ways to do this are through some GUI library or through syscalls. Which would you prefer?

**Comment by adzo261** [comment]
Great!
As in future, I would like to add support for setting wallpaper on Windows, some cross-platform GUI lib would be best.
I prefer [PyGTK](https://python-gtk-3-tutorial.readthedocs.io/en/latest/).
For reference-[See](https://www.blog.pythonlibrary.org/2015/08/18/getting-your-screen-resolution-with-python/)
What say?

**Comment by yashBhosale** [comment]
Can do. Traveling at the moment, but I should be able to get this done by the end of the weekend.

**Comment by adzo261** [comment]
Okay, I am labeling the issue as 'Assigned'.
Looking forward to your PR this weekend.

**Comment by yashBhosale** [comment]
Hey, I need push access to be able to actually add my branch to your repo.

**Comment by adzo261** [comment]
You can create a Pull Request(PR).
 Learn about it here:
[First Contributions](https://github.com/firstcontributions/first-contributions)
For any open source project on GitHub to which you want to contribute ,you need to fork that project, create a branch of your feature,commit and create a Pull Request for your branch.  
Read Contributing part of:
[Readme](https://github.com/adzo261/todo-wallpaper-cli/blob/master/README.md)

**Comment by yashBhosale** [comment]
To be able to create a branch I need push access

**Comment by adzo261** [comment]
Giving Push access is for collaborators in a team.
For contributors outside of team or owner organization, one needs to fork the repository and create a branch on that fork. And once you commit and push to that branch, one needs to create a Pull Request(Requesting the owner of Original Repository to merge your branch).
And the owner of the repository will accept the Pull Request.
This is how Open Source Contributions work.
For that, you don't need Push access.
Please read this tutorial if it is your first time contributing to open source:
[First Contributions](https://github.com/firstcontributions/first-contributions)
Take your time.

**Comment by yashBhosale** [comment]
Ah. My bad, just created the Pull request

**Comment by adzo261** [comment]
Can you use PyQt?
It's quite hectic to install gi object on different OS.
Also while updating requirements.txt, do mention the version of module you installed using pip.
You can see the version by using the command `pip freeze`.
